package com.scau.learnshufa.entity;

import java.io.Serializable;

public class Authentication implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.identitytype
     *
     * @mbg.generated
     */
    private String identitytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.credential
     *
     * @mbg.generated
     */
    private String credential;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.ifverifiled
     *
     * @mbg.generated
     */
    private String ifverifiled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_auths
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.ID
     *
     * @return the value of user_auths.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.ID
     *
     * @param id the value for user_auths.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.user_id
     *
     * @return the value of user_auths.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.user_id
     *
     * @param userId the value for user_auths.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.userid
     *
     * @return the value of user_auths.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.userid
     *
     * @param userid the value for user_auths.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.identitytype
     *
     * @return the value of user_auths.identitytype
     *
     * @mbg.generated
     */
    public String getIdentitytype() {
        return identitytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.identitytype
     *
     * @param identitytype the value for user_auths.identitytype
     *
     * @mbg.generated
     */
    public void setIdentitytype(String identitytype) {
        this.identitytype = identitytype == null ? null : identitytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.credential
     *
     * @return the value of user_auths.credential
     *
     * @mbg.generated
     */
    public String getCredential() {
        return credential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.credential
     *
     * @param credential the value for user_auths.credential
     *
     * @mbg.generated
     */
    public void setCredential(String credential) {
        this.credential = credential == null ? null : credential.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.ifverifiled
     *
     * @return the value of user_auths.ifverifiled
     *
     * @mbg.generated
     */
    public String getIfverifiled() {
        return ifverifiled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.ifverifiled
     *
     * @param ifverifiled the value for user_auths.ifverifiled
     *
     * @mbg.generated
     */
    public void setIfverifiled(String ifverifiled) {
        this.ifverifiled = ifverifiled == null ? null : ifverifiled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auths
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", userid=").append(userid);
        sb.append(", identitytype=").append(identitytype);
        sb.append(", credential=").append(credential);
        sb.append(", ifverifiled=").append(ifverifiled);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auths
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Authentication other = (Authentication) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getIdentitytype() == null ? other.getIdentitytype() == null : this.getIdentitytype().equals(other.getIdentitytype()))
            && (this.getCredential() == null ? other.getCredential() == null : this.getCredential().equals(other.getCredential()))
            && (this.getIfverifiled() == null ? other.getIfverifiled() == null : this.getIfverifiled().equals(other.getIfverifiled()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auths
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getIdentitytype() == null) ? 0 : getIdentitytype().hashCode());
        result = prime * result + ((getCredential() == null) ? 0 : getCredential().hashCode());
        result = prime * result + ((getIfverifiled() == null) ? 0 : getIfverifiled().hashCode());
        return result;
    }
}