package com.scau.learnshufa.entity;

import java.io.Serializable;

public class Label implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_label.label_id
     *
     * @mbg.generated
     */
    private Long labelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_label.article_id
     *
     * @mbg.generated
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_label.resource_id
     *
     * @mbg.generated
     */
    private Long resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_label.label_name
     *
     * @mbg.generated
     */
    private String labelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_label.label_alias
     *
     * @mbg.generated
     */
    private String labelAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_label.label_desc
     *
     * @mbg.generated
     */
    private String labelDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sf_label
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_label.label_id
     *
     * @return the value of sf_label.label_id
     *
     * @mbg.generated
     */
    public Long getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_label.label_id
     *
     * @param labelId the value for sf_label.label_id
     *
     * @mbg.generated
     */
    public void setLabelId(Long labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_label.article_id
     *
     * @return the value of sf_label.article_id
     *
     * @mbg.generated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_label.article_id
     *
     * @param articleId the value for sf_label.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_label.resource_id
     *
     * @return the value of sf_label.resource_id
     *
     * @mbg.generated
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_label.resource_id
     *
     * @param resourceId the value for sf_label.resource_id
     *
     * @mbg.generated
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_label.label_name
     *
     * @return the value of sf_label.label_name
     *
     * @mbg.generated
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_label.label_name
     *
     * @param labelName the value for sf_label.label_name
     *
     * @mbg.generated
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_label.label_alias
     *
     * @return the value of sf_label.label_alias
     *
     * @mbg.generated
     */
    public String getLabelAlias() {
        return labelAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_label.label_alias
     *
     * @param labelAlias the value for sf_label.label_alias
     *
     * @mbg.generated
     */
    public void setLabelAlias(String labelAlias) {
        this.labelAlias = labelAlias == null ? null : labelAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_label.label_desc
     *
     * @return the value of sf_label.label_desc
     *
     * @mbg.generated
     */
    public String getLabelDesc() {
        return labelDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_label.label_desc
     *
     * @param labelDesc the value for sf_label.label_desc
     *
     * @mbg.generated
     */
    public void setLabelDesc(String labelDesc) {
        this.labelDesc = labelDesc == null ? null : labelDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_label
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", labelId=").append(labelId);
        sb.append(", articleId=").append(articleId);
        sb.append(", resourceId=").append(resourceId);
        sb.append(", labelName=").append(labelName);
        sb.append(", labelAlias=").append(labelAlias);
        sb.append(", labelDesc=").append(labelDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_label
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Label other = (Label) that;
        return (this.getLabelId() == null ? other.getLabelId() == null : this.getLabelId().equals(other.getLabelId()))
            && (this.getArticleId() == null ? other.getArticleId() == null : this.getArticleId().equals(other.getArticleId()))
            && (this.getResourceId() == null ? other.getResourceId() == null : this.getResourceId().equals(other.getResourceId()))
            && (this.getLabelName() == null ? other.getLabelName() == null : this.getLabelName().equals(other.getLabelName()))
            && (this.getLabelAlias() == null ? other.getLabelAlias() == null : this.getLabelAlias().equals(other.getLabelAlias()))
            && (this.getLabelDesc() == null ? other.getLabelDesc() == null : this.getLabelDesc().equals(other.getLabelDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_label
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLabelId() == null) ? 0 : getLabelId().hashCode());
        result = prime * result + ((getArticleId() == null) ? 0 : getArticleId().hashCode());
        result = prime * result + ((getResourceId() == null) ? 0 : getResourceId().hashCode());
        result = prime * result + ((getLabelName() == null) ? 0 : getLabelName().hashCode());
        result = prime * result + ((getLabelAlias() == null) ? 0 : getLabelAlias().hashCode());
        result = prime * result + ((getLabelDesc() == null) ? 0 : getLabelDesc().hashCode());
        return result;
    }
}