package com.scau.learnshufa.entity;

import java.io.Serializable;

public class Question implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_question.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_question.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_question.publish_time
     *
     * @mbg.generated
     */
    private String publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_question.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_question.source_url
     *
     * @mbg.generated
     */
    private String sourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_question.readNum
     *
     * @mbg.generated
     */
    private Integer readnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_question.comment
     *
     * @mbg.generated
     */
    private Integer comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_question.topic
     *
     * @mbg.generated
     */
    private String topic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_question.sort
     *
     * @mbg.generated
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_question.likes
     *
     * @mbg.generated
     */
    private Integer likes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_question.backup
     *
     * @mbg.generated
     */
    private String backup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sf_question.text
     *
     * @mbg.generated
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sf_question
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_question.ID
     *
     * @return the value of sf_question.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_question.ID
     *
     * @param id the value for sf_question.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_question.name
     *
     * @return the value of sf_question.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_question.name
     *
     * @param name the value for sf_question.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_question.publish_time
     *
     * @return the value of sf_question.publish_time
     *
     * @mbg.generated
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_question.publish_time
     *
     * @param publishTime the value for sf_question.publish_time
     *
     * @mbg.generated
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime == null ? null : publishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_question.author
     *
     * @return the value of sf_question.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_question.author
     *
     * @param author the value for sf_question.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_question.source_url
     *
     * @return the value of sf_question.source_url
     *
     * @mbg.generated
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_question.source_url
     *
     * @param sourceUrl the value for sf_question.source_url
     *
     * @mbg.generated
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_question.readNum
     *
     * @return the value of sf_question.readNum
     *
     * @mbg.generated
     */
    public Integer getReadnum() {
        return readnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_question.readNum
     *
     * @param readnum the value for sf_question.readNum
     *
     * @mbg.generated
     */
    public void setReadnum(Integer readnum) {
        this.readnum = readnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_question.comment
     *
     * @return the value of sf_question.comment
     *
     * @mbg.generated
     */
    public Integer getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_question.comment
     *
     * @param comment the value for sf_question.comment
     *
     * @mbg.generated
     */
    public void setComment(Integer comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_question.topic
     *
     * @return the value of sf_question.topic
     *
     * @mbg.generated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_question.topic
     *
     * @param topic the value for sf_question.topic
     *
     * @mbg.generated
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_question.sort
     *
     * @return the value of sf_question.sort
     *
     * @mbg.generated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_question.sort
     *
     * @param sort the value for sf_question.sort
     *
     * @mbg.generated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_question.likes
     *
     * @return the value of sf_question.likes
     *
     * @mbg.generated
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_question.likes
     *
     * @param likes the value for sf_question.likes
     *
     * @mbg.generated
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_question.backup
     *
     * @return the value of sf_question.backup
     *
     * @mbg.generated
     */
    public String getBackup() {
        return backup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_question.backup
     *
     * @param backup the value for sf_question.backup
     *
     * @mbg.generated
     */
    public void setBackup(String backup) {
        this.backup = backup == null ? null : backup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sf_question.text
     *
     * @return the value of sf_question.text
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sf_question.text
     *
     * @param text the value for sf_question.text
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_question
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", publishTime=").append(publishTime);
        sb.append(", author=").append(author);
        sb.append(", sourceUrl=").append(sourceUrl);
        sb.append(", readnum=").append(readnum);
        sb.append(", comment=").append(comment);
        sb.append(", topic=").append(topic);
        sb.append(", sort=").append(sort);
        sb.append(", likes=").append(likes);
        sb.append(", backup=").append(backup);
        sb.append(", text=").append(text);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_question
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Question other = (Question) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getPublishTime() == null ? other.getPublishTime() == null : this.getPublishTime().equals(other.getPublishTime()))
                && (this.getAuthor() == null ? other.getAuthor() == null : this.getAuthor().equals(other.getAuthor()))
                && (this.getSourceUrl() == null ? other.getSourceUrl() == null : this.getSourceUrl().equals(other.getSourceUrl()))
                && (this.getReadnum() == null ? other.getReadnum() == null : this.getReadnum().equals(other.getReadnum()))
                && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
                && (this.getTopic() == null ? other.getTopic() == null : this.getTopic().equals(other.getTopic()))
                && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
                && (this.getLikes() == null ? other.getLikes() == null : this.getLikes().equals(other.getLikes()))
                && (this.getBackup() == null ? other.getBackup() == null : this.getBackup().equals(other.getBackup()))
                && (this.getText() == null ? other.getText() == null : this.getText().equals(other.getText()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_question
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPublishTime() == null) ? 0 : getPublishTime().hashCode());
        result = prime * result + ((getAuthor() == null) ? 0 : getAuthor().hashCode());
        result = prime * result + ((getSourceUrl() == null) ? 0 : getSourceUrl().hashCode());
        result = prime * result + ((getReadnum() == null) ? 0 : getReadnum().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getTopic() == null) ? 0 : getTopic().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getLikes() == null) ? 0 : getLikes().hashCode());
        result = prime * result + ((getBackup() == null) ? 0 : getBackup().hashCode());
        result = prime * result + ((getText() == null) ? 0 : getText().hashCode());
        return result;
    }
}