package com.scau.learnshufa.mapper;

import com.scau.learnshufa.entity.Article;

import java.util.List;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_article
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_article
     *
     * @mbg.generated
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_article
     *
     * @mbg.generated
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_article
     *
     * @mbg.generated
     */
    Article selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Article record);

    /**
     * 查询所有的文章
     * @return
     */
    List<Article> selectArticles();

    /**
     * 查询所有文章中最新的7篇文章
     * @return
     */
    List<Article> selectLatestSevenArticle();

    /**
     * 查询最所有文章中热门的7篇文章
     * @return
     */
    List<Article> selectMostPopularSevenArticle();

    /**
     * 查询英语文章中最新的6篇文章
     */
    List<Article> selectLatestTenEnglishArticles();

    /**
     * 查询英语文章中热门的6篇文章
     */
    List<Article> selectMostPopularEightEnglishArticles();

}