package com.scau.learnshufa.mapper;

import com.scau.learnshufa.entity.Authentication;

public interface AuthenticationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auths
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auths
     *
     * @mbg.generated
     */
    int insert(Authentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auths
     *
     * @mbg.generated
     */
    int insertSelective(Authentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auths
     *
     * @mbg.generated
     */
    Authentication selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auths
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Authentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auths
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Authentication record);
}