package com.scau.learnshufa.mapper;

import com.scau.learnshufa.entity.Label;

import java.util.List;

public interface LabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_label
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_label
     *
     * @mbg.generated
     */
    int insert(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_label
     *
     * @mbg.generated
     */
    int insertSelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_label
     *
     * @mbg.generated
     */
    Label selectByPrimaryKey(Long labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_label
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_label
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Label record);

    /**
     * 查询所有标签
     * @return
     */
    List<Label> selectLabels();
}