package com.scau.learnshufa.mapper;

import com.scau.learnshufa.entity.Link;

public interface LinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_link
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_link
     *
     * @mbg.generated
     */
    int insert(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_link
     *
     * @mbg.generated
     */
    int insertSelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_link
     *
     * @mbg.generated
     */
    Link selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_link
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_link
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Link record);
}