package com.scau.learnshufa.mapper;

import com.scau.learnshufa.entity.Penman;

public interface PenmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_penman
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_penman
     *
     * @mbg.generated
     */
    int insert(Penman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_penman
     *
     * @mbg.generated
     */
    int insertSelective(Penman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_penman
     *
     * @mbg.generated
     */
    Penman selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_penman
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Penman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sf_penman
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Penman record);
}